-- =============================================================================
-- Dialekt: Oracle Database (SQL DDL, składnia zgodna z Oracle 19c+).
--
-- Ten skrypt NIE jest uruchamiany w środowisku szkoleniowym — nie ma tu
-- instancji bazy danych. Plik służy wyłącznie do czytania, wyjaśniania
-- i analizy przez model AI.
-- =============================================================================
--
-- Migracja 001 — rejestr transakcji.
--
-- Tabelaryczny odpowiednik kontraktu `Transaction` ze ścieżki TypeScript tego
-- samego repozytorium (`src/model.ts`): te same pola biznesowe, ten sam
-- podział ról między kolumnami — kierunek operacji niesie TYP_OPERACJI,
-- nigdy znak kwoty.

CREATE TABLE transakcje (
    id_transakcji       NUMBER(19)
                             GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1)
                             NOT NULL,
    id_operacji         VARCHAR2(20 CHAR)   NOT NULL,
    nr_rachunku         CHAR(26 CHAR)       NOT NULL,
    kwota               BINARY_DOUBLE       NOT NULL,
    waluta              CHAR(3 CHAR)        NOT NULL,
    typ_operacji        VARCHAR2(10 CHAR)   NOT NULL,
    data_ksiegowania    TIMESTAMP(0)        NOT NULL,
    data_waluty         DATE                NOT NULL,
    tytul               VARCHAR2(140 CHAR)  NOT NULL,
    plik_zrodlowy       VARCHAR2(60 CHAR),
    utworzono_dnia      TIMESTAMP(6)        DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_transakcje
        PRIMARY KEY (id_transakcji),
    CONSTRAINT uq_transakcje_id_operacji
        UNIQUE (id_operacji),
    CONSTRAINT ck_transakcje_nr_rachunku
        CHECK (REGEXP_LIKE(nr_rachunku, '^[0-9]{26}$')),
    CONSTRAINT ck_transakcje_kwota
        CHECK (kwota > 0),
    CONSTRAINT ck_transakcje_waluta
        CHECK (waluta IN ('PLN', 'EUR', 'USD')),
    CONSTRAINT ck_transakcje_typ_operacji
        CHECK (typ_operacji IN ('UZNANIE', 'OBCIAZENIE'))
);

COMMENT ON TABLE transakcje IS
    'Rejestr transakcji rachunków rozliczeniowych — jedna operacja na wiersz. Zasilany importem wyciągów źródłowych, patrz PLIK_ZRODLOWY.';

COMMENT ON COLUMN transakcje.id_transakcji IS
    'Klucz surogatowy tabeli. Bez znaczenia biznesowego.';

COMMENT ON COLUMN transakcje.id_operacji IS
    'Identyfikator operacji nadany przez system źródłowy (np. OP-2026-08-0001). Unikalny w skali całego rejestru.';

COMMENT ON COLUMN transakcje.nr_rachunku IS
    'Numer rachunku w formacie NRB — 26 cyfr, zapisywane bez spacji.';

COMMENT ON COLUMN transakcje.kwota IS
    'Kwota operacji w walucie wskazanej kolumną WALUTA, zawsze dodatnia. Kierunek operacji niesie TYP_OPERACJI, nigdy znak kwoty.';

COMMENT ON COLUMN transakcje.waluta IS
    'Waluta operacji: PLN, EUR albo USD.';

COMMENT ON COLUMN transakcje.typ_operacji IS
    'Kierunek operacji: UZNANIE zwiększa saldo rachunku, OBCIAZENIE je zmniejsza.';

COMMENT ON COLUMN transakcje.data_ksiegowania IS
    'Moment zaksięgowania operacji w systemie źródłowym.';

COMMENT ON COLUMN transakcje.data_waluty IS
    'Data waluty operacji — od niej naliczane są odsetki.';

COMMENT ON COLUMN transakcje.tytul IS
    'Tytuł operacji, tak jak podał go zleceniodawca.';

COMMENT ON COLUMN transakcje.plik_zrodlowy IS
    'Nazwa pliku wyciągu, z którego zaimportowano wiersz. NULL dla operacji wprowadzonych ręcznie.';

COMMENT ON COLUMN transakcje.utworzono_dnia IS
    'Znacznik czasu zapisania wiersza w rejestrze (audyt techniczny) — nie mylić z DATA_KSIEGOWANIA.';

-- Historia rachunku i naliczanie odsetek odpytują po numerze rachunku
-- i dacie waluty łącznie.
CREATE INDEX ix_transakcje_rachunek_wal ON transakcje (nr_rachunku, data_waluty);

-- Wsparcie dla raportu dobowego (grupowanie po dniu księgowania i walucie) —
-- indeks funkcyjny odpowiadający dokładnie klauzuli GROUP BY raportu
-- w raport_dzienny.sql.
CREATE INDEX ix_transakcje_dzien_waluta ON transakcje (TRUNC(data_ksiegowania), waluta);
